[package]
name = "nezuo/lapis"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

[dependencies]
Promise = "evaera/promise@4.0.0"
TestEZ = "roblox/testez@0.4.1"

[server-dependencies]
DataStoreServiceMock = "nezuo/data-store-service-mock@0.1.4"
