[package]
name = "nezuo/lapis"
version = "0.2.5"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.toml", "LICENSE"]
realm = "server"

[dependencies]
Promise = "evaera/promise@4.0.0"

[dev-dependencies]
Midori = "nezuo/midori@0.1.3"
DataStoreServiceMock = "nezuo/data-store-service-mock@0.3.5"
