[package]
name = "davidnurkkala/lapis"
version = "0.2.4"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.toml", "LICENSE"]
realm = "server"

[dependencies]
Promise = "evaera/promise@4.0.0"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
DataStoreServiceMock = "nezuo/data-store-service-mock@0.3.0"
